### ISSUE TITLE
Allow seeMe=teamnumber

### ISSUE THREAD

**Issue by SLiebald** [m-o-p/labsystem#67]
Similar to the "seeMe=all" tag in the URL it should be possible to use "seeMe=20X" to only display elements of a specific team (20X).
Currently only a long id can be used for this which can't be memorized. Therefore one always have to find a link to that view (e.g. from the overview of all teams) and then click on it.

**Comment by m-o-p** [comment]
Added this feature. It loads the member with the first status record for a lab now when you give the team number as parameter.
