### ISSUE TITLE
Reword "correct" (question/answer) -> "mark" question

### ISSUE THREAD

**Issue by ralphholz-usyd** [m-o-p/labsystem#96]
To improve the ilab's English: please change the wording of "to correct" a question (in the interfaces) to "mark the question".

"to correct" does not carry the German connotation of "marking", it literally means to rectify something. You can trust me on this after teaching multiple years at English-speaking unis...

**Comment by m-o-p** [comment]
Fixed with 63dabd65dab85ac6409eddb1380a4f6ba3061fd9
